### ISSUE TITLE
UnknownNodeError.BaseError

### ISSUE THREAD

**Issue by domoritz** [xiag-ag/typescript-to-json-schema#1]
I'm trying to use this library for vega-lite (https://github.com/vega/vega-lite) but I can't get the type or path right:
`./node_modules/.bin/typescript-to-json-schema --path 'src/spec.ts' --type 'ExtendedSpec'`

As a user, how would I get help with this?

**Comment by navossoc** [comment]
Same

**Comment by mrix** [comment]
Sorry for the late reply. I've just come back from my vacation.
Please check the error message with the current `master`. It looks like this:
```
$ bin/typescript-to-json-schema --path "/tmp/vega-lite/src/spec.ts" --type "ExtendedSpec"
UnknownNodeError: Unknown node type "export namespace Mark {" at /tmp/vega-lite/src/mark.ts(3,0)
```

I still think it would be better if we could get information about the usage of the unknown node, and not its definition. Will try to add this feature this week.

**Comment by navossoc** [comment]
I got your latest commit and build it...
Then I have tried it again...

This time I got this error:
> NoRootTypeError: No root type "Test" found

Test.ts
```ts
class Test {
    name: string;
    age: number;
}
```

I have tried with an interface named Test too and I got the same error.

> typescript-to-json-schema --path "Test.ts" -t "Test"

I'm missing something here?

**Comment by mrix** [comment]
Hi @navossoc.

1. this tool does not support classes. I think using interfaces is more suitable for describing data structure
2. this tool does not work with private types. you need to mark the type with `export`
