### ISSUE TITLE
typeof types

### ISSUE THREAD

**Issue by domoritz** [xiag-ag/typescript-to-json-schema#14]
Hi, maintainer of https://github.com/YousefED/typescript-json-schema here. It's been getting increasingly difficult to maintain typescript-json-schema and you seem to have found a cleaner approach. I need the json schema generator for https://github.com/vega/vega-lite. The one thing that seems missing for my use case is support for `typeof` types. I saw in the readme that you don't plan to implement it. I could take a stab at it but wanted to hear your thoughts first.

**Comment by mrix** [comment]
Closed via #16 and #17
