### ISSUE TITLE
Errors throw errors themselves

### ISSUE THREAD

**Issue by marcoqu** [xiag-ag/typescript-to-json-schema#30]
Many errors (eg. `DiagnosticError`, `UnknownNodeError`) throw errors themselves because, even though you automatically assign constructor paraments, these get assigned *after* the `super()` call to the parent class.

It gets compiled to this:

    constructor(diagnostics) {
        super();
        this.diagnostics = diagnostics;
    }

Since `super()` calls `captureStackTrace` that accesses getters such as `name` and `message`, and those access the constructor parameters, you get errors such as `Cannot read property 'map' of undefined`

**Comment by mrix** [comment]
Hi @marcoqu. Can you please provide any examples reproducing this error?


This code has no errors at runtime (node v8.11.2, typescript v2.8.3, ts-node v6.0.3):

```ts
abstract class BaseError implements Error {
    public readonly stack!: string;

    protected constructor() {
        console.log("BaseError.constructor.pre");
        Error.captureStackTrace(this, this.constructor);
        console.log("BaseError.constructor.post");
    }

    public abstract get name(): string;
    public abstract get message(): string;
}

class SomeError extends BaseError {
    public constructor(private data: object) {
        super();
        console.log("SomeError.constructor");
    }

    public get name(): string {
        console.log("SomeError.name");
        return "SomeError";
    }
    public get message(): string {
        console.log("SomeError.message");
        return JSON.stringify(this.data);
    }
}


const error = new SomeError({ some: "data" });
// outputs
// BaseError.constructor.pre
// BaseError.constructor.post
// SomeError.constructor
```

**Comment by marcoqu** [comment]
Sorry, this is not an issue on your side.  
VSCode extension host is providing a custom stacktrace formatter (by overriding [prepareStackTrace](https://github.com/Microsoft/vscode/blob/186eb2a582c70d30a1542bb2b53bfb956b1cd02d/src/vs/workbench/node/extensionHostMain.ts#L111)) that accesses `get message()` and `get name()`.
Don't really know how to get around this, though. 😕
